name: Keep Render Alive

on:
  schedule:
    - cron: '*/14 * * * *'  # Cada 14 minutos
  
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping site
        run: curl -f https://vfa-digital-landing-1.onrender.com/
